Fix for DatabaseTests
alexweissman/UserFrosting pull request #1175
Opened 2021-08-05 16:48 UTC by ktecho

At this point, all the tables from the standard migration have been created in previous tests, so tables like `users` or `roles` cannot be created again.

2021-08-06 07:25 UTC, Silic0nS0ldier commented
To confirm, this PR fixes the database tests so that they can be rerun successfully. Correct?

2021-08-06 08:21 UTC, ktecho commented
@Silic0nS0ldier No, this fixes are needed to run the tests in a separate database/connection than the main one.

I cannot explain why it works here in github, but it's needed for the tests to pass in a separate MySQL.

I was talking about this with @lcharette yesterday... Maybe the tests are always running in an "in memory" database so we don't need to clear the database between tests?

2021-08-06 08:27 UTC, ktecho commented
@Silic0nS0ldier I want to update the `docker-compose` file to run another MySQL for tests, so you can do `php bakery test` whenever you want and run the tests in the devel environment without having to run another set of containers.

I have it running in our project, but this fixes are needed for the tests to pass.

2021-10-27 01:26 UTC, lcharette requested changes
Fun fact, I encountered the same issue while working on 5.0 and before looking at this in details... The main thing is DatabaseTest is forced to run on in-memory database due to an hardcoded string (https://github.com/userfrosting/UserFrosting/issues/1069). 

Long story short, this whole mess is fixed in [5.0](https://github.com/userfrosting/sprinkle-core/blob/8042a983a53a0a0720a10aad3d6170a8ffba646a/tests/Integration/Database/DatabaseTests.php#L121), but I'm still willing to merge that in 4.x if requested change is applied.

2023-11-25 02:26 UTC, lcharette commented
Closing this, as it's not relevant with UF5 anymore

2023-11-25 02:26 UTC, closed without merging